chore: Refactor to remove transitive dependency in report package (#6610)
#### Details

https://github.com/microsoft/accessibility-insights-action/pull/1624 is
failing with the following error:

```
Cannot find module '@microsoft/applicationinsights-core-js' from '../../../node_modules/accessibility-insights-report/drop/index.js'
```

This dependency was added in #6476, which introduced `isNullOrUndefined`
from the telemetry module. While using other's code is a great idea, it
adds a strange dependency (and one that isn't called out) to the report
package. I've added our own version of `isNullOrUndefined` instead of
using the one from applicationinsights.

##### Motivation

We should be able to update the report package at any point in time

##### Context

<!-- Are there any parts that you've intentionally left out-of-scope for
a later PR to handle? -->

<!-- Were there any alternative approaches you considered? What
tradeoffs did you consider? -->
As mentioned above, we could just add the transitive dependency but it
seems like the wrong option here. Other places in the code explicitly
check for `foo === null || foo === undefined`, which is just nasty here.

#### Pull request checklist
<!-- If a checklist item is not applicable to this change, write "n/a"
in the checkbox -->
- [n/a] Addresses an existing issue: #0000
- [x] Ran `yarn fastpass`
- [n/a] Added/updated relevant unit test(s) (and ran `yarn test`)
- [n/a] Verified code coverage for the changes made. Check coverage
report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic
tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See
`CONTRIBUTING.md`.
- [n/a] (UI changes only) Added screenshots/GIFs to description above
- [n/a] (UI changes only) Verified usability with NVDA/JAWS