chore: TypeScript Cleanup 5.0 Part 4 for Errors - includeStepsText,featureFlagStoreData,deps,requirementState,outline, (#7292)
#### Details

As part of Typescript migration added/removed the error causing fields.

##### Motivation

TypeScript 5.0 has marked some options as deprecated. We can temporarily
override these deprecations, but the documented plan is for the ability
to override the flag to go away in TypeScript 5.5

##### Context

1. **includeStepsText={false}**

- **Error:** No overload matches this call.Type '{
needsReviewCardsViewData: CardsViewModel;
needsReviewCardSelectionMessageCreator: CardSelectionMessageCreator;
automatedChecksCardsViewData: CardsViewModel }' is not assignable to
type 'IntrinsicAttributes &
IntrinsicClassAttributes<AssessmentIssuesTestView> &
Readonly<AssessmentIssuesTestViewProps> & Readonly<...>'
- Property 'includeStepsText' does not exist on type
'IntrinsicAttributes &
IntrinsicClassAttributes<AssessmentIssuesTestView> &
Readonly<AssessmentIssuesTestViewProps>
- In file
src/DetailsView/components/default-test-view-container-provider.tsx
getting error for includeStepsText. Added the property in reference
file.

2. **requirementState={requirementState}**

- **Error:** Type '{ deps: AdhocTabStopsTestViewDeps;
failureInstanceState: FailureInstanceState; requirementState:
TabStopRequirementState; }' is not assignable to type
'IntrinsicAttributes & TabStopsFailedInstancePanelProps & { children?:
ReactNode; }'.
- Property 'requirementState' does not exist on type
'IntrinsicAttributes & TabStopsFailedInstancePanelProps & { children?:
ReactNode; }'.
- As per the previous commits, someone removed from the reference
interface/type but didn't remove from actual usage.
3.  **featureFlagStoreData={featureFlagStoreData}**

- **Error:** Type '{ deps: DetailsViewLeftNavDeps; featureFlagStoreData:
FeatureFlagStoreData; pivotKey: DetailsViewPivotType; }' is not
assignable to type 'IntrinsicAttributes &
IntrinsicClassAttributes<Switcher> & Readonly<SwitcherProps> &
Readonly<...>'.
- Property 'featureFlagStoreData' does not exist on type
'IntrinsicAttributes & IntrinsicClassAttributes<Switcher>
- As per the previous commits, someone removed from the reference
interface/type but didn't remove from actual usage.

4. **Deps**

- **Error:** Type '{ deps: ReportExportComponentDeps; isOpen: boolean;
htmlFileName: string; jsonFileName: string; description: string;
htmlExportData: string; jsonExportData: string; ... 9 more ...;
exportResultsClickedTelemetry: (reportExportFormat: ReportExportFormat,
selectedServiceKey: ReportExportServiceKey, event: MouseEvent<.....' is
not assignable to type 'IntrinsicAttributes & ExportDialogProps & {
children?: ReactNode; }'.
- Property 'deps' does not exist on type 'IntrinsicAttributes &
ExportDialogProps & { children?: ReactNode; }'.
- As per the previous commits, someone removed from the reference
interface/type but didn't remove from actual usage.

5. **outline: '3px dashed'**

- **Error:** Type '{ fontColor: string; background: string; text:
string; fontWeight: string; fontSize: string; outline: string; }' is not
assignable to type 'TextBoxConfig'.
- Object literal featureFlagData={featureFlags}may only specify known
properties, and 'outline' does not exist in type 'TextBoxConfig'.
- As per the previous commits, someone removed from the reference
interface/type but didn't remove from actual usage.

6. **featureFlagData={featureFlags}**

- **Error:** Type '{ deps: LaunchPanelHeaderDeps; popupWindow: Window;
header: this; featureFlagData: FeatureFlagStoreData; }' is not
assignable to type 'IntrinsicAttributes & HamburgerMenuButtonProps & {
children?: ReactNode; }'.
- Property 'featureFlagData' does not exist on type 'IntrinsicAttributes
& HamburgerMenuButtonProps & { children?: ReactNode; }'.
- As per the previous commits, someone removed from the reference
interface/type but didn't remove from actual usage.

7. **isContextMenuVisible**

- **Error:** Argument of type '{ target: any; isContextMenuVisible:
boolean; }' is not assignable to parameter of type
'LaunchPanelHeaderState | ((prevState: Readonly<LaunchPanelHeaderState>,
props: Readonly<LaunchPanelHeaderProps>) => LaunchPanelHeaderState |
Pick<...>) | Pick<...>'.
- Object literal may only specify known properties, and
'isContextMenuVisible' does not exist in type 'LaunchPanelHeaderState
- As per the previous commits, someone removed from the reference
interface/type but didn't remove from actual usage.

8. **featureFlagStoreData**

- **Error:** Property 'featureFlagStoreData' does not exist on type
'IntrinsicAttributes & IntrinsicClassAttributes<FastPassReportSummary>
- As per the previous commits, someone removed from the reference
interface/type but didn't remove from actual usage.

9. **deps:null**

- **Error:** Argument of type '{ id: string; header: JSX.Element;
content: JSX.Element; headingLevel: number; deps: null; }' is not
assignable to parameter of type 'ReportCollapsibleContainerProps'.
- Object literal may only specify known properties, and 'deps' does not
exist in type 'ReportCollapsibleContainerProps'.
- As per the previous commits, someone removed from the reference
interface/type but didn't remove from actual usage.

10.  **testName: 'test-name'**

- **Error:** Type '{ key: string; testName: string; rules: string[];
testType: VisualizationType; }' is not assignable to type
'Readonly<Partial<RuleAnalyzerConfiguration>>'.
- Object literal may only specify known properties, and 'testName' does
not exist in type 'Readonly<Partial<RuleAnalyzerConfiguration>>'.

11. **openGettingStartedDialog**

- **Error:** Type '{ deps: LaunchPanelHeaderDeps; title: string;
subtitle: string; openGettingStartedDialog: any; openFeedbackDialog:
any; popupWindow: Window; featureFlags: FeatureFlagStoreData;
openAdhocToolsPanel: () => void; dropdownClickHandler:
DropdownClickHandler; }' is not assignable to type
'LaunchPanelHeaderProps'.
- Object literal may only specify known properties, and
'openGettingStartedDialog' does not exist in type
'LaunchPanelHeaderProps'.
- As per the previous commits, someone removed from the reference
interface/type but didn't remove from actual usage.

12. **deps**

- **Error:** Type '{ deps: { collapsibleControl:
(collapsibleControlProps: ReportCollapsibleContainerProps) =>
JSX.Element; }; failed: { url: string; numFailures: number;
reportLocation: string; }[]; passed: { ...; }[]; unscannable: { ...;
}[]; }' is not assignable to type 'SummaryScanResults'.
- Object literal may only specify known properties, and 'deps' does not
exist in type 'SummaryScanResults'.
- As per the previous commits, someone removed from the reference
interface/type but didn't remove from actual usage.


#### Pull request checklist
<!-- If a checklist item is not applicable to this change, write "n/a"
in the checkbox -->
- [x] Addresses an existing issue:
#[0000](https://github.com/microsoft/accessibility-insights-web/pull/6611)
- [ ] Ran `yarn fastpass`
- [ ] Added/updated relevant unit test(s) (and ran `yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report
at: `<rootDir>/test-results/unit/coverage`
- [x ] PR title *AND* final merge commit title both start with a
semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See
`CONTRIBUTING.md`.
- [ ] (UI changes only) Added screenshots/GIFs to description above
- [ ] (UI changes only) Verified usability with NVDA/JAWS

---------

Co-authored-by: Prachi Naigaonkar <v-prachin@microsoft.com>