fix(mv3-part-8): Check for defined telemetry trace (#6039)
#### Details

Bug in sending telemetry for mv3 extensions: 
```
serviceWorker.bundle.js:683 Error while processing browser RuntimeOnMessage event:  TypeError: Cannot set properties of undefined (setting 'name')
```

##### Motivation

Fix mv3 bug

##### Context

It's not clear why `this.applicationInsights.context.telemetryTrace` is
undefined in mv3 extensions but not mv2 extensions, but checked with
@madalynrose (who added this line) and it appears to be non-vital, so we
should be safe to only set the name when telemetryTrace is defined.

#### Pull request checklist
<!-- If a checklist item is not applicable to this change, write "n/a"
in the checkbox -->
- [n/a] Addresses an existing issue: #0000
- [x] Ran `yarn null:autoadd`
- [x] Ran `yarn fastpass`
- [x] Added/updated relevant unit test(s) (and ran `yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report
at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic
tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See
`CONTRIBUTING.md`.
- [n/a] (UI changes only) Added screenshots/GIFs to description above
- [n/a] (UI changes only) Verified usability with NVDA/JAWS