chore: update tsconfig target/lib to es2017 (#1081)
Now that we're on a more recent TypeScript version, we have the ability to update our JS transpilation target. This PR updates the JS output we bundle to allow the use of ES2017 constructs, rather than transpiling down to an ES5 target.

Per [the best compatibility table I was able to find](https://kangax.github.io/compat-table/es2016plus/), everything in ES2017 is supported in Chrome stable and latest Edge Insiders. Everything besides shared memory/atomic constructs (which we don't use) is supported in the oldest Firefox extended support release.

The primary benefit of this is getting much better stack traces from async test failures:

**before**
```
  ● First time Dialog › should have reasonable stacks when an deeply async test fails

    TimeoutError: waiting for selector "#selector-that-does-not-exist" failed: timeout 5000ms exceeded

      112 |     public async waitForSelector(selector: string, options?: Puppeteer.WaitForSelectorOptions): Promise<Puppeteer.ElementHandle<Element>> {
      113 |         return await this.screenshotOnError(
    > 114 |             async () => await this.underlyingPage.waitForSelector(selector, { timeout: DEFAULT_PAGE_ELEMENT_WAIT_TIMEOUT_MS, ...options }),
          |                                                   ^
      115 |         );
      116 |     }
      117 |

      at new WaitTask (node_modules/puppeteer/lib/DOMWorld.js:561:28)
      at DOMWorld._waitForSelectorOrXPath (node_modules/puppeteer/lib/DOMWorld.js:490:22)
      at DOMWorld.waitForSelector (node_modules/puppeteer/lib/DOMWorld.js:444:17)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:628:47)
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:1089:29)
      at PopupPage.<anonymous> (src/tests/end-to-end/common/page-controllers/page.ts:114:51)
      at step (src/tests/end-to-end/common/page-controllers/page.ts:42:23)
      at Object.next (src/tests/end-to-end/common/page-controllers/page.ts:23:53)
      at src/tests/end-to-end/common/page-controllers/page.ts:17:71
      at Object.<anonymous>.__awaiter (src/tests/end-to-end/common/page-controllers/page.ts:13:12)
      at src/tests/end-to-end/common/page-controllers/page.ts:114:13
      at PopupPage.<anonymous> (src/tests/end-to-end/common/page-controllers/page.ts:262:26)
      at step (src/tests/end-to-end/common/page-controllers/page.ts:42:23)
      at Object.next (src/tests/end-to-end/common/page-controllers/page.ts:23:53)
      at src/tests/end-to-end/common/page-controllers/page.ts:17:71
      at Object.<anonymous>.__awaiter (src/tests/end-to-end/common/page-controllers/page.ts:13:12)
      at PopupPage.Object.<anonymous>.Page.screenshotOnError (src/tests/end-to-end/common/page-controllers/page.ts:542:16)
      at PopupPage.<anonymous> (src/tests/end-to-end/common/page-controllers/page.ts:113:27)
      at step (src/tests/end-to-end/common/page-controllers/page.ts:42:23)
      at Object.next (src/tests/end-to-end/common/page-controllers/page.ts:23:53)
      at src/tests/end-to-end/common/page-controllers/page.ts:17:71
      at Object.<anonymous>.__awaiter (src/tests/end-to-end/common/page-controllers/page.ts:13:12)
      at PopupPage.Object.<anonymous>.Page.waitForSelector (src/tests/end-to-end/common/page-controllers/page.ts:225:16)
      at Object.<anonymous> (src/tests/end-to-end/tests/popup/first-time-dialog.test.ts:62:42)
      at step (src/tests/end-to-end/tests/popup/first-time-dialog.test.ts:31:23)
      at Object.next (src/tests/end-to-end/tests/popup/first-time-dialog.test.ts:12:53)
      at fulfilled (src/tests/end-to-end/tests/popup/first-time-dialog.test.ts:3:58) 
```

**after**
```
  ● First time Dialog › should have reasonable stacks when an deeply async test fails

    TimeoutError: waiting for selector "#selector-that-does-not-exist" failed: timeout 5000ms exceeded

      112 |     public async waitForSelector(selector: string, options?: Puppeteer.WaitForSelectorOptions): Promise<Puppeteer.ElementHandle<Element>> {
      113 |         return await this.screenshotOnError(
    > 114 |             async () => await this.underlyingPage.waitForSelector(selector, { timeout: DEFAULT_PAGE_ELEMENT_WAIT_TIMEOUT_MS, ...options }),
          |                                                   ^
      115 |         );
      116 |     }
      117 |

      at new WaitTask (node_modules/puppeteer/lib/DOMWorld.js:561:28)
      at DOMWorld._waitForSelectorOrXPath (node_modules/puppeteer/lib/DOMWorld.js:490:22)
      at DOMWorld.waitForSelector (node_modules/puppeteer/lib/DOMWorld.js:444:17)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:628:47)
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:1089:29)
      at screenshotOnError (src/tests/end-to-end/common/page-controllers/page.ts:114:51)
      at PopupPage.screenshotOnError (src/tests/end-to-end/common/page-controllers/page.ts:262:26)
      at PopupPage.waitForSelector (src/tests/end-to-end/common/page-controllers/page.ts:113:27)
      at Object.it (src/tests/end-to-end/tests/popup/first-time-dialog.test.ts:62:42)
```

A secondary benefit is a slight (2-3%) reduction in bundle sizes (this didn't have a significant impact on TTI perf). 

**before**:
```
> dir .\drop\production\extension\bundle\*.js
    Directory: Q:\repos\accessibility-insights-web\drop\production\extension\bundle

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        8/15/2019   4:30 PM        3096716 background.bundle.js
-a----        8/15/2019   4:30 PM        3473816 detailsView.bundle.js
-a----        8/15/2019   4:30 PM          87172 devtools.bundle.js
-a----        8/15/2019   4:30 PM        3076872 injected.bundle.js
-a----        8/15/2019   4:30 PM        2269628 insights.bundle.js
-a----        8/15/2019   4:30 PM        2648035 popup.bundle.js
```

**after**:
```
> dir .\drop\production\extension\bundle\*.js
    Directory: Q:\repos\accessibility-insights-web\drop\production\extension\bundle

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        8/15/2019   4:28 PM        3018530 background.bundle.js
-a----        8/15/2019   4:28 PM        3394145 detailsView.bundle.js
-a----        8/15/2019   4:28 PM          84910 devtools.bundle.js
-a----        8/15/2019   4:28 PM        3006291 injected.bundle.js
-a----        8/15/2019   4:28 PM        2259382 insights.bundle.js
-a----        8/15/2019   4:28 PM        2582914 popup.bundle.js
```

Another secondary benefit is that it improves snapshot files that involve certain applications proxy objects/mocks; generally, cases where we snapshot a proxy no longer contain useless `[Function: function]` placeholders in cases where we don't specify a particular method as part of a test, and start containing the names of functions that we *do* specify when they are named things.