chore(deps): update node in CI builds to 14.19.0 (#5139)
#### Details

This PR bumps the version of Node we use in CI builds on both GitHub Actions and Azure DevOps to the latest v14 (`14.19.0`).

This is primarily in the hopes of resolving an issue we've seen in a few recent PR builds for dependabot PRs where builds fail in webpack with an error that looks like this:

```
Running "concurrent:webpack-all" (concurrent) task

    Running "exec:webpack-prod" (exec) task
    >> internal/child_process/serialization.js:70
    >>       yield deserializer.readValue();
    >>                          ^
    >> 
    >> Error: Unable to deserialize cloned data.
    >>     at parseChannelMessages (internal/child_process/serialization.js:70:26)
    >>     at parseChannelMessages.next (<anonymous>)
    >>     at Pipe.channel.onread (internal/child_process.js:599:18)
    >> Exited with code: 1.
    >> Error executing child process: Error: Process exited with code 1.
```

This symptom is similar to the one resolved by https://github.com/nodejs/node/pull/38728, which is included in 14.17.4

##### Motivation

* Keep deps up to date
* Attempt to avoid an error blocking PR builds (#5134, #5135, #5136)

##### Context

n/a

#### Pull request checklist
<!-- If a checklist item is not applicable to this change, write "n/a" in the checkbox -->
- [n/a] Addresses an existing issue: #0000
- [x] Ran `yarn fastpass`
- [n/a] Added/updated relevant unit test(s) (and ran `yarn test`)
- [n/a] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [n/a] (UI changes only) Added screenshots/GIFs to description above
- [n/a] (UI changes only) Verified usability with NVDA/JAWS