chore(deps-dev): Bump eslint from 8.55.0 to 8.56.0 (#7171)
Bumps [eslint](https://github.com/eslint/eslint) from 8.55.0 to 8.56.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/eslint/eslint/releases">eslint's
releases</a>.</em></p>
<blockquote>
<h2>v8.56.0</h2>
<h2>Features</h2>
<ul>
<li><a
href="https://github.com/eslint/eslint/commit/0dd9704c4751e1cd02039f7d6485fee09bbccbf6"><code>0dd9704</code></a>
feat: Support custom severity when reporting unused disable directives
(<a
href="https://redirect.github.com/eslint/eslint/issues/17212">#17212</a>)
(Bryan Mishkin)</li>
<li><a
href="https://github.com/eslint/eslint/commit/31a7e3fde491e36496b54e8905c766b31162d776"><code>31a7e3f</code></a>
feat: fix no-restricted-properties false negatives with unknown objects
(<a
href="https://redirect.github.com/eslint/eslint/issues/17818">#17818</a>)
(Arka Pratim Chaudhuri)</li>
</ul>
<h2>Bug Fixes</h2>
<ul>
<li><a
href="https://github.com/eslint/eslint/commit/7d5e5f68849ae80caec0fc96ecceebccd348deec"><code>7d5e5f6</code></a>
fix: <code>TypeError: fs.exists is not a function</code> on read-only
file system (<a
href="https://redirect.github.com/eslint/eslint/issues/17846">#17846</a>)
(Francesco Trotta)</li>
<li><a
href="https://github.com/eslint/eslint/commit/74739c849bbb6547b0e555ed8bb2ba1cbe0fdce4"><code>74739c8</code></a>
fix: suggestion with invalid syntax in no-promise-executor-return rule
(<a
href="https://redirect.github.com/eslint/eslint/issues/17812">#17812</a>)
(Bryan Mishkin)</li>
</ul>
<h2>Documentation</h2>
<ul>
<li><a
href="https://github.com/eslint/eslint/commit/90077199fe519953f9af8664bf947db4e4958514"><code>9007719</code></a>
docs: update link in ways-to-extend.md (<a
href="https://redirect.github.com/eslint/eslint/issues/17839">#17839</a>)
(Amel SELMANE)</li>
<li><a
href="https://github.com/eslint/eslint/commit/3a22236f8d10af8a5bcafe56092651d3d681c99d"><code>3a22236</code></a>
docs: Update README (GitHub Actions Bot)</li>
<li><a
href="https://github.com/eslint/eslint/commit/54c3ca6f2dcd2a7afd53f42fc32055a25587259e"><code>54c3ca6</code></a>
docs: fix migration-guide example (<a
href="https://redirect.github.com/eslint/eslint/issues/17829">#17829</a>)
(Tanuj Kanti)</li>
<li><a
href="https://github.com/eslint/eslint/commit/4391b71e62b15e54b0493f0dce1ea053ebbc0689"><code>4391b71</code></a>
docs: check config comments in rule examples (<a
href="https://redirect.github.com/eslint/eslint/issues/17815">#17815</a>)
(Francesco Trotta)</li>
<li><a
href="https://github.com/eslint/eslint/commit/fd2836342c2be4751b05fe0ba7cece17d1edecc8"><code>fd28363</code></a>
docs: remove mention about ESLint stylistic rules in readme (<a
href="https://redirect.github.com/eslint/eslint/issues/17810">#17810</a>)
(Zwyx)</li>
<li><a
href="https://github.com/eslint/eslint/commit/48ed5a6dad478a14d3e823f137455c523f373e0b"><code>48ed5a6</code></a>
docs: Update README (GitHub Actions Bot)</li>
</ul>
<h2>Chores</h2>
<ul>
<li><a
href="https://github.com/eslint/eslint/commit/ba6af85c7d8ba55d37f8663aee949d148e441c1a"><code>ba6af85</code></a>
chore: upgrade <code>@​eslint/js</code><a
href="https://github.com/8"><code>@​8</code></a>.56.0 (<a
href="https://redirect.github.com/eslint/eslint/issues/17864">#17864</a>)
(Milos Djermanovic)</li>
<li><a
href="https://github.com/eslint/eslint/commit/60a531a9c0811ddf718e26b9136e133f580b6c36"><code>60a531a</code></a>
chore: package.json update for <code>@​eslint/js</code> release
(Jenkins)</li>
<li><a
href="https://github.com/eslint/eslint/commit/ba87a0651a65b52c3ac442b512dd9f4c2b4c5f57"><code>ba87a06</code></a>
chore: update dependency markdownlint to ^0.32.0 (<a
href="https://redirect.github.com/eslint/eslint/issues/17783">#17783</a>)
(renovate[bot])</li>
<li><a
href="https://github.com/eslint/eslint/commit/9271d10d9eabeafb0129a090f29191bfd14273c0"><code>9271d10</code></a>
chore: add GitHub issue template for docs issues (<a
href="https://redirect.github.com/eslint/eslint/issues/17845">#17845</a>)
(Josh Goldberg ✨)</li>
<li><a
href="https://github.com/eslint/eslint/commit/70a686b3c1feac5eca98bbff9bd67175f550d5db"><code>70a686b</code></a>
chore: Convert rule tests to FlatRuleTester (<a
href="https://redirect.github.com/eslint/eslint/issues/17819">#17819</a>)
(Nicholas C. Zakas)</li>
<li><a
href="https://github.com/eslint/eslint/commit/f3a599d34c7080fc0b2c9a60b5e54dc98c22867c"><code>f3a599d</code></a>
chore: upgrade eslint-plugin-unicorn to v49.0.0 (<a
href="https://redirect.github.com/eslint/eslint/issues/17837">#17837</a>)
(唯然)</li>
<li><a
href="https://github.com/eslint/eslint/commit/905d4b75ab2df42aba30622cee0f66b511397e2c"><code>905d4b7</code></a>
chore: upgrade eslint-plugin-eslint-plugin v5.2.1 (<a
href="https://redirect.github.com/eslint/eslint/issues/17838">#17838</a>)
(唯然)</li>
<li><a
href="https://github.com/eslint/eslint/commit/4d7c3ce246e6b499f472342ef59496a47cc033d6"><code>4d7c3ce</code></a>
chore: update eslint-plugin-n v16.4.0 (<a
href="https://redirect.github.com/eslint/eslint/issues/17836">#17836</a>)
(唯然)</li>
<li><a
href="https://github.com/eslint/eslint/commit/fd0c60c3be1f213e5a6d69d8a3248e963619e155"><code>fd0c60c</code></a>
ci: unpin Node.js 21.2.0 (<a
href="https://redirect.github.com/eslint/eslint/issues/17821">#17821</a>)
(Francesco Trotta)</li>
</ul>
</blockquote>
</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>