chore: Add script to check ClearlyDefined status in dependabot PR builds (#6859)
#### Details

This adds a script to check the script to detect gaps in ClearlyDefined.
It keys off the branch name to determine the following:
1. Is this a dependabot PR? (exit if no)
2. If so, what is the namespace, package, and package version?
3. Is this namespace + package in the curated exclusion list? (exit if
yes)
4. Does ClearlyDefined include an entry for this update? Succeed if yes,
fail if no)

This check is _not_ a blocking check, so it's possible to squash and
merge without it passing, which would be appropriate for a "deps-dev"
PR. The intent is to make the human aware of the potential impact and to
force a decision. Note that while this will catch PR's that update
versions of existing packages, it will _not_ catch PR's that add new
packages. That will be the responsibility of the task that creates
`NOTICE.html` and will live in a separate repo

##### Motivation

Progress toward #6636, which suggests changes to help ensure that our
`NOTICE.html` file remains correct. Once this change is merged, we
should be able to replace the manually managed `NOTICE.html` file with
the generated version

##### Sample output:

###### Non-Dependabot PR:
```
VERBOSE: Resolved Inputs: PipeLineType=action, BranchName=check-clearlydefined-for-dependabot
Not a dependabot PR, skipping check
```

###### Dependabot PR of a package that ClearlyDefined has already
harvested:
```
VERBOSE: Resolved Inputs: PipeLineType=action, BranchName=dependabot/npm_and_yarn/react-router-dom-6.14.1
Getting data from https://api.clearlydefined.io/definitions/npm/npmjs/-/react-router-dom/6.14.1
VERBOSE: GET with 0-byte payload
VERBOSE: received 6541-byte response of content type application/json
VERBOSE: Content encoding: utf-[8](https://github.com/microsoft/accessibility-insights-web/actions/runs/5755005810/job/15601503428?pr=6859#step:5:9)
ClearlyDefined has a definition for this package version.
```

###### Dependabot PR of a package that ClearlyDefined has not yet
harvested:
```
VERBOSE: Resolved Inputs: PipeLineType=action, BranchName=dependabot/npm_and_yarn/react-router-dom-6.14.10
Getting data from https://api.clearlydefined.io/definitions/npm/npmjs/-/react-router-dom/6.14.10
VERBOSE: GET with 0-byte payload
VERBOSE: received 4[8](https://github.com/microsoft/accessibility-insights-web/actions/runs/5755057600/job/15601673883?pr=6859#step:5:9)2-byte response of content type application/json
VERBOSE: Content encoding: utf-8
Error: ClearlyDefined does not have a definition for this package version.
If this is a development component, you may safely ignore this warning.

If this is a production component, please do the following:
1. Request that ClearlyDefined harvest information for this package version
2. Wait for the harvest to complete -- check at [https://clearlydefined.io](https://clearlydefined.io)
3. Re-run the failed build
4. Once the PR build passes, merge the PR
5. If necessary, add this package to clearly-defined-exclusions.json and include it in your PR.
   Merge the PR once the build passes.
Error: Process completed with exit code 1.
```

##### Context

<!-- Are there any parts that you've intentionally left out-of-scope for
a later PR to handle? -->

<!-- Were there any alternative approaches you considered? What
tradeoffs did you consider? -->
The intent is to use this script across multiple repos, which is why it
includes support for action, ado, and local versions. In an ideal world
we would have this in a single location, but we're not ready to do that
just yet.

#### Pull request checklist
<!-- If a checklist item is not applicable to this change, write "n/a"
in the checkbox -->
- [x] Addresses an existing issue: #6636
- [x] Ran `yarn fastpass`
- [n/a] Added/updated relevant unit test(s) (and ran `yarn test`)
- [n/a] Verified code coverage for the changes made. Check coverage
report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic
tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See
`CONTRIBUTING.md`.
- [n/a] (UI changes only) Added screenshots/GIFs to description above
- [n/a] (UI changes only) Verified usability with NVDA/JAWS