feat(mv3-part7): Convert mv3 extension to use build generated JSON validator (#5975)
#### Details

Fixes mv3 bug with loading assessments. Repro steps:

1. Open mv3 canary/ dev assessment
2. Try to load assessment file
3. See nothing happens in details view, see following errors in console:
```
exception-telemetry-listener.ts:87 Error compiling schema, function code: const schema2 = scope.schema[2];const schema1 = scope.schema[1];return function validate1(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;const _errs1 = errors;if(!(((typeof data == "number") && (!(data % 1) && !isNaN(data))) && (isFinite(data)))){validate1.errors = [{instancePath,schemaPath:"#/definitions/nonNegativeInteger/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];return false;}if(errors === _errs1){if((typeof data == "number") && (isFinite(data))){if(data < 0 || isNaN(data)){validate1.errors = [{instancePath,schemaPath:"#/definitions/nonNegativeInteger/minimum",keyword:"minimum",params:{comparison: ">=", limit: 0},message:"must be >= 0"}];return false;}}}validate1.errors = vErrors;return errors === 0;}
```
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

##### Motivation

Feature work

##### Context

The root cause of this bug is that AJV, the library we use to validate the JSON input of assessment files, requires `unsafe-eval` in in the app's content security policy (see their docs: https://ajv.js.org/security.html#content-security-policy). This isn't a problem in mv2, we just add the appropriate line to the manifest: https://github.com/microsoft/accessibility-insights-web/blob/main/Gruntfile.js#L518. But with mv3, chrome no longer allows extensions to include `unsafe-eval` in their manifest CSP, so this is no longer an option. As a solution, this PR migrates us to use AJV's standalone validation code process instead: https://ajv.js.org/standalone.html.

A few changes were necessary to convert to the standalone process:

1. Add json generator package. This allows us to build the validator generation code separately from the rest of the codebase.
2. Add extra steps to mv3 build process to (A) build the validator generation code, (B) run the validation generator, and (C) place the generated validator in the expected file such that it can be accessed by the rest of the code.
3. Add extra logic to `load-assessment-data-validator.ts` to determine if the build generated validator is populated or if we should fallback on using the old, dynamically generated validator. We theoretically could convert all products to use the new, build generated validator and remove the old code, but I decided to only convert the mv3 extension to minimize changes to the other products that share this logic.
5. In the case that we use the build generated validator, also check that the assessments data matches the enabled feature flags. With the dynamically generated validator, we are able to check on the fly which feature flags are enabled/ disabled, and as a result, the schema that the validator checks against excludes any assessments that are behind disabled feature flags. We can't check which flags are disabled when we're generating the validator on build, so instead we include all assessments in the build generated validator schema and separately check in `LoadAssessmentDataValidator.uploadedDataIsValid` that none of the assessments in the uploaded data are behind disabled feature flags.

#### Pull request checklist
<!-- If a checklist item is not applicable to this change, write "n/a" in the checkbox -->
- [n/a] Addresses an existing issue: #0000
- [x] Ran `yarn null:autoadd`
- [x] Ran `yarn fastpass`
- [x] Added/updated relevant unit test(s) (and ran `yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [n/a] (UI changes only) Added screenshots/GIFs to description above
- [n/a] (UI changes only) Verified usability with NVDA/JAWS